apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-actix
spec:
  replicas: 5
  selector:
    matchLabels:
      app: main-actix
  template:
    metadata:
      labels:
        app: main-actix
    spec:
      containers:
      - name: main-actix
        image: 112573511757.dkr.ecr.us-east-1.amazonaws.com/task-tracker:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "500M"
            cpu: "512m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: main-actix
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
      name: myingress
spec:
  defaultBackend:
    service:
      name: main-service
      port:
        number: 8080
