apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
  namespace: eks-task-tracker-app
  labels:
    app: eks-task-tracker-app
spec:
  selector:
    app: eks-task-tracker-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080