apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment
  namespace: eks-task-tracker-app
  labels:
    app: eks-task-tracker-linux-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-task-tracker-linux-app
  template:
    metadata:
      labels:
        app: eks-task-tracker-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: eks-task-tracker-linux-app
        image: 112573511757.dkr.ecr.us-east-1.amazonaws.com/task-tracker:latest
        ports:

        # - name: http
        - containerPort: 8080
        imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux